"""cria tabela oee_agregado

Revision ID: 78158cb80324
Revises: b603b70b4988
Create Date: 2026-08-01 12:48:15.453110

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78158cb80324"
down_revision: str | Sequence[str] | None = "b603b70b4988"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oee_agregado",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("maquina_id", sa.String(length=50), nullable=False),
        sa.Column("janela_inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("janela_fim", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disponibilidade", sa.Double(), nullable=False),
        sa.Column("performance", sa.Double(), nullable=False),
        sa.Column("qualidade", sa.Double(), nullable=False),
        sa.Column("oee", sa.Double(), nullable=False),
        sa.Column("unidades_produzidas", sa.BigInteger(), nullable=True),
        sa.Column("unidades_refugo", sa.BigInteger(), nullable=True),
        sa.Column("tempo_planejado_s", sa.Double(), nullable=True),
        sa.Column("tempo_rodando_s", sa.Double(), nullable=True),
        sa.Column(
            "ts_calculo",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["maquina_id"],
            ["maquinas.maquina_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "maquina_id",
            "janela_inicio",
            "janela_fim",
            name="uq_oee_agregado_maquina_janela",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oee_agregado")
    # ### end Alembic commands ###
