"""cria tabelas iniciais: maquinas, turnos, motivos_parada, telemetria hypertable,
estado_maquina, parada, producao

Revision ID: 7f955f80083c
Revises:
Create Date: 2026-08-01 11:20:35.995768

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f955f80083c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maquinas",
        sa.Column("maquina_id", sa.String(length=50), nullable=False),
        sa.Column("galpao", sa.String(length=10), nullable=False),
        sa.Column("linha", sa.String(length=10), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("tempo_ciclo_ideal_s", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("maquina_id"),
    )
    op.create_table(
        "motivos_parada",
        sa.Column("motivo_codigo", sa.String(length=30), nullable=False),
        sa.Column("descricao", sa.String(length=100), nullable=False),
        sa.Column("planejada", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("motivo_codigo"),
    )
    op.create_table(
        "turnos",
        sa.Column("turno_id", sa.String(length=10), nullable=False),
        sa.Column("nome", sa.String(length=30), nullable=False),
        sa.Column("inicio", sa.Time(), nullable=False),
        sa.Column("fim", sa.Time(), nullable=False),
        sa.PrimaryKeyConstraint("turno_id"),
    )
    op.create_table(
        "estado_maquina",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("maquina_id", sa.String(length=50), nullable=False),
        sa.Column("ts_sensor", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("estado_anterior", sa.String(length=20), nullable=False),
        sa.Column(
            "ts_ingestao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["maquina_id"],
            ["maquinas.maquina_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_estado_maquina_maquina_ts",
        "estado_maquina",
        ["maquina_id", "ts_sensor"],
        unique=False,
    )
    op.create_table(
        "parada",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("maquina_id", sa.String(length=50), nullable=False),
        sa.Column("motivo_codigo", sa.String(length=30), nullable=False),
        sa.Column("motivo_descricao", sa.String(length=100), nullable=False),
        sa.Column("planejada", sa.Boolean(), nullable=False),
        sa.Column("ts_sensor", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ts_ingestao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["maquina_id"],
            ["maquinas.maquina_id"],
        ),
        sa.ForeignKeyConstraint(
            ["motivo_codigo"],
            ["motivos_parada.motivo_codigo"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_parada_maquina_ts", "parada", ["maquina_id", "ts_sensor"], unique=False
    )
    op.create_index("ix_parada_motivo", "parada", ["motivo_codigo"], unique=False)
    op.create_table(
        "producao",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("maquina_id", sa.String(length=50), nullable=False),
        sa.Column("ts_sensor", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unidades_produzidas", sa.BigInteger(), nullable=False),
        sa.Column("unidades_refugo", sa.BigInteger(), nullable=False),
        sa.Column("ordem_producao", sa.String(length=30), nullable=False),
        sa.Column(
            "ts_ingestao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["maquina_id"],
            ["maquinas.maquina_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_producao_maquina_ts", "producao", ["maquina_id", "ts_sensor"], unique=False
    )
    op.create_table(
        "telemetria",
        sa.Column("maquina_id", sa.String(length=50), nullable=False),
        sa.Column("ts_sensor", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rpm", sa.Float(), nullable=False),
        sa.Column("voltas_acumuladas", sa.BigInteger(), nullable=False),
        sa.Column("temperatura_c", sa.Float(), nullable=False),
        sa.Column("vibracao_mm_s", sa.Float(), nullable=False),
        sa.Column(
            "ts_ingestao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["maquina_id"],
            ["maquinas.maquina_id"],
        ),
        sa.PrimaryKeyConstraint("maquina_id", "ts_sensor"),
    )
    # Hypertable TimescaleDB — fora de transacao (DDL proprio do TimescaleDB)
    with op.get_context().autocommit_block():
        op.execute(
            "SELECT create_hypertable("
            "'telemetria', by_range('ts_sensor'), "
            "if_not_exists => TRUE"
            ")"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Hypertable e removida automaticamente com DROP TABLE — nao precisa de
    # comando separado. A ordem de drop ja esta correta (telemetria primeiro).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telemetria")
    op.drop_index("ix_producao_maquina_ts", table_name="producao")
    op.drop_table("producao")
    op.drop_index("ix_parada_motivo", table_name="parada")
    op.drop_index("ix_parada_maquina_ts", table_name="parada")
    op.drop_table("parada")
    op.drop_index("ix_estado_maquina_maquina_ts", table_name="estado_maquina")
    op.drop_table("estado_maquina")
    op.drop_table("turnos")
    op.drop_table("motivos_parada")
    op.drop_table("maquinas")
    # ### end Alembic commands ###
