"""adiciona content_hash unique em estado_maquina, parada, producao

Revision ID: b603b70b4988
Revises: 7f955f80083c
Create Date: 2026-08-01 11:51:31.774823

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b603b70b4988"
down_revision: str | Sequence[str] | None = "7f955f80083c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "estado_maquina", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(None, "estado_maquina", ["content_hash"])
    op.add_column(
        "parada", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(None, "parada", ["content_hash"])
    op.add_column(
        "producao", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(None, "producao", ["content_hash"])
    op.drop_index(op.f("telemetria_ts_sensor_idx"), table_name="telemetria")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("telemetria_ts_sensor_idx"),
        "telemetria",
        [sa.literal_column("ts_sensor DESC")],
        unique=False,
    )
    op.drop_constraint(None, "producao", type_="unique")
    op.drop_column("producao", "content_hash")
    op.drop_constraint(None, "parada", type_="unique")
    op.drop_column("parada", "content_hash")
    op.drop_constraint(None, "estado_maquina", type_="unique")
    op.drop_column("estado_maquina", "content_hash")
    # ### end Alembic commands ###
